theme = "dark_magenta"

[keys.normal]
S-down = "page_cursor_half_down"
S-up = "page_cursor_half_up"

A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

A-e = ":vsplit-new"
A-w = ":buffer-close!"
A-q = ":quit!"

C-s = ":w!"
C-c = ":clipboard-yank"
C-v = ":clipboard-paste-before"
C-d = ["keep_primary_selection", "search_selection", "select_mode"]

[keys.insert]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

A-e = ":vsplit-new"
A-w = ":buffer-close!"
A-q = ":quit!"

C-s = ":w!"
C-c = ":clipboard-yank"
C-v = ":clipboard-paste-before"
C-d = ["keep_primary_selection", "search_selection", "select_mode"]

[keys.select]
C-s = ":w!"
C-c = ":clipboard-yank"
C-v = ":clipboard-paste-before"
C-d = ["search_selection", "extend_search_next"]


[editor.file-picker]
hidden = false
