[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = [
  "--parser",
  "css",
  "--tab-width",
  "4",
] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[language-server.glsl_analyzer]
command = "glsl_analyzer"

[[language]]
name = "glsl"
language-servers = ["glsl_analyzer"]
auto-format = true
